### PR TITLE
[New Feature]Add TaskBuild DSL to describe a graph!

### PR DESCRIPTION
**Pull request by netcan**
I add Taskbuild dsl to enhancing describing graph topological structure, before using dsl you can describe as below:
```cpp
tf::Taskflow taskflow;
tf::Task A = taskflow.emplace([] () {}).name("A");
tf::Task B = taskflow.emplace([] () {}).name("B");
tf::Task C = taskflow.emplace([] () {}).name("C");
tf::Task D = taskflow.emplace([] () {}).name("D");
tf::Task E = taskflow.emplace([] () {}).name("E");
A.precede(B, C, E); 
C.precede(D);
B.precede(D, E);
```
After by using DSL, it more **expressive**:
```cpp
def_task((A), { std::cout << "TaskA\n"; };);
def_task((B), { std::cout << "TaskB\n"; };);
def_task((C), { std::cout << "TaskC\n"; };);
def_task((D), { std::cout << "TaskD\n"; };);
def_task((E), { std::cout << "TaskE\n"; };);

auto tasks = taskbuild(
  task(A)
    -> fork(B, C)
    -> task(D),
  merge(A, B)
    -> task(E)
)(taskflow);
```

### Feature
- if using `fork(a,b,c,d) -> merge(e,f,g,h)` will generate Cartesian product all 16 links!
- support a chain such as `__task(a) -> __task(b) -> __task(c) -> ...`
- using `def_task((TASK), {})` to define a task
- using `def_task((TASK, Context), {})` to support capture arguments by context(pass context)

More examples, see
- simple_dsl.cpp
- visualization_dsl.cpp
- conditction_dsl.cpp

For More details about implementation, see [https://netcan.github.io/2020/08/30/C-元编程之代码生成：设计并实现拓扑结构DSL/](https://netcan.github.io/2020/08/30/C-%E5%85%83%E7%BC%96%E7%A8%8B%E4%B9%8B%E4%BB%A3%E7%A0%81%E7%94%9F%E6%88%90%EF%BC%9A%E8%AE%BE%E8%AE%A1%E5%B9%B6%E5%AE%9E%E7%8E%B0%E6%8B%93%E6%89%91%E7%BB%93%E6%9E%84DSL/)

### CODE REVIEW

**Comment by tsung-wei-huang** [comment]
@netcan this is definitely a very interesting feature I would like to include. I saw your dsl may be extended to another higher-level layer and, keep in mind, taskflow can integrate control flow (conditional tasking) into task graph. Would you be interested in having a call and collaborate on this? You may shoot me an email from Contact [here](https://taskflow.github.io/).

**Comment by netcan** [comment]
I'm interested in the taskflow project and thank you for contributing on parallel computing. It's a powerful project.
After reading the docs, I found that the structure of the description topological structure was not intuitive enough, if using EDSL(Embeded domain specifc language) looks like `dot' will more intuitive. 
I designed and implemented a DSL in my spare time, now support primitive is:
- `__def_task`: a task factory to invoke: `FlowBuilder::emplace(TaskFactory{}())`
- `__fork(...)`: many task destination
- `__merge(...)`: many task  source
- `__link(task)`: a task source

I found the a condition that also is a task, so condition can easy integration in graph. but I think it can declare in DSL, such as:
- __merge(A, B, C, D) -> __if(Cond, E, F)
- __merge(A, B, C, D) -> __optional(Cond, E)
- __if(Cond, E, F) -> C
- __link(A) -> __if(Cond, A, B)

**Comment by tsung-wei-huang** [comment]
@netcan would you please fix the compilation error in gcc 6? https://travis-ci.com/github/taskflow/taskflow/builds/181806822

**Comment by netcan** [comment]
> @netcan would you please fix the compilation error in gcc 6? https://travis-ci.com/github/taskflow/taskflow/builds/181806822

All compiler pass except msvc.

**Comment by tsung-wei-huang** [comment]
@netcan perfect, thanks! I am a bit unfavored for the naming "__" because the double underscore ("__") in identifiers is reserved for the compiler's internal use according to the ANSI-C standard. I saw in your code that is defined for Macro. In taskflow, macro definition starts with `TF_`, for example, `TF_VERSION`. I suggest making it `tf::dsl::link`, but it requires changes to parameter pack in functions. With a new namespace dsl, it makes contributions and naming easier. How do you think?

**Comment by netcan** [comment]
> @netcan perfect, thanks! I am a bit unfavored for the naming `__` because the double underscore (`__`) in identifiers is reserved for the compiler's internal use according to the ANSI-C standard. I saw in your code that is defined for Macro. In taskflow, macro definition starts with `TF_`, for example, `TF_VERSION`. I suggest making it `tf::dsl::link`, `tf::dsl::merge`, etc, but it requires changes to parameter pack in functions. With a new namespace `dsl`, it makes contributions and naming easier and cleaner. How do you think?

I agree

**Comment by netcan** [comment]
using `def_taskc` to pass context need at least `g++7`, it use 'capture *this' feature to pass(copy self safety) to lambda, so in lamba can use directly context's fields.
so this feature also needs msvc using `/std:c++17` flag.

I use REPEAT MACRO to auto trailing `-> void` on each links(chain) for avoiding writing `chain(...)` macro in `taskbuild`, It seems has a problem in msvc.

**Comment by netcan** [comment]
@tsung-wei-huang Almost finished,  but `capture *this` feature([P0018R3](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0018r3.html)X) doesn't not support in g++5/6.

**Comment by tsung-wei-huang** [comment]
@netcan thanks for the great effort. I have merged it to the branch and temporarily disable the build of dsl in the CI. Here is a few TODO items if you are interested in helping:

1. I named this project to `TaskflowDSL` and created a target in Cmake - ideally, it should be enabled when the compiler support C++17 but I haven't finished it
2. I have created a `dsl.hpp` as the top-level include `#include<taskflow/dsl.hpp>` for using `TaskflowDSL`
3. I think the naming of `fork` and `merge` should be more precise - I don't know what they mean exactly in the dsl context. Is fork one-to-many or many-to-many? In this sense, does it mean `precede`? Same for merge, one-to-many or man-to-many?

**Comment by netcan** [comment]
> @netcan thanks for the great effort! I have merged it to the branch and temporarily disable the build of dsl in the CI. Here is a few TODO items if you are interested in helping:
> 
> 1. I named this project to `TaskflowDSL` and created a target in Cmake - ideally, it should be enabled when the compiler support C++17 but I haven't finished it
> 2. I have created a `dsl.hpp` as the top-level include `#include<taskflow/dsl.hpp>` for using `TaskflowDSL`
> 3. I think the naming of `fork` and `merge` should be more precise - I don't know what they mean exactly in the dsl context. Is fork one-to-many or many-to-many? In this sense, does it mean `precede`? Same for merge, one-to-many or man-to-many?

`fork` and `merge` is an alias to refer to `some_task`, it means there has many tasks connect from or to. But them also have meaning to express 'one to many'(`task(A) -> fork(B, C)`), 'many to one'(`merge(B, C) -> task(A)`), or 'many to many'(`some_task(A, B) -> some_task(C, D)`), it will translate to 'one to one' relationship set, generating such as `A.precede(B)` code.

**Comment by tsung-wei-huang** [comment]
some_task(A, B) -> some_task(C, D) will give A.precede(C) and B.precede(D), respectively? Or it gives cross product A->B, A->D, B->C, and B->D?

**Comment by netcan** [comment]
> some_task(A, B) -> some_task(C, D) will give A.precede(C) and B.precede(D), respectively? Or it gives cross product A->B, A->D, B->C, and B->D?

It gives cross product: A->C, A->D, B->C, B->D, generating A.precede(C), A.precede(D), B.precede(C), B.precede(D) correspondingly.

**Comment by tsung-wei-huang** [comment]
@netcan I see, thanks!

**Pull request merged**
