### PR TITLE
can pause task impl

### PR DESCRIPTION
**Pull request by yangxingpping**
[https://github.com/taskflow/taskflow/issues/215#issue-685539450](url)

I am also want something like this. for example
A game instance[taskflow] compose of several components[task].
Task 1, create game instance; Task 2, deal players input; Task 3 clean up game instance(update player's level...)
And task 2 is driven by players' input, and May be looped for many time.

### CODE REVIEW

**Comment by tsung-wei-huang** [comment]
@yangxingpping this seems interesting. Would you please try to help fix the compiler error of the CI so I can play around with it when it is done?

**Comment by yangxingpping** [comment]
https://github.com/yangxingpping/taskflow/commit/c84324860bdc13c8150e57d347a43fb3b5f61299
Yes,  fixed.

**Comment by tsung-wei-huang** [comment]
@yangxingpping can you explain the difference among pausable return, `true`, `false`, and `nullopt`?

**Comment by yangxingpping** [comment]
true, resumeTask will call from paused task ( paused task will call again); false, resume Task will skip paused task; nullopt, task like staic static task

**Comment by yangxingpping** [comment]
Does that can be achieved by other exists tasks?

**Comment by tsung-wei-huang** [comment]
Not really - I was just a bit confused by the tri-state return :)

**Comment by tsung-wei-huang** [comment]
@yangxingpping is it possible to do this at a taskflow scale? I am a bit skeptical about the practical use of pausing the graph from a task, especially when condition tasks come into play. However, being able to pause a submitted taskflow is more frequently used, based on my experience.

```cpp
tf::Taskflow taskflow;

// create some tasks

tf::Future<void> future = executor.run(taskflow);

// right, now we support cancel through the following:
// future.cancel();

// It is very useful if we can pause it as well
future.pause();
future.resume();
```

**Comment by yangxingpping** [comment]
I want to have an method to control pause or continue taskflow accurately, so I think this should be done before call executor.run(taskflow).

**Comment by junlinmessi** [comment]
What is the smallest granularity to pause? A Node?

**Comment by tsung-wei-huang** [comment]
@yangxingpping thanks for your excellent effort. Your present implementation is cleaner than before (returning `std::optional<int>`). I will read the code as soon as possible and merge it to the branch.

**Comment by tsung-wei-huang** [comment]
@yangxingpping Would you be able to provide some unittests for this new feature? I suggest creating a new file `unittests/pausable.cpp`. Also, `pausable` is probably better than `can pause`.

**Comment by yangxingpping** [comment]
@tsung-wei-huang Yes, I will do in this week.

**Comment by yangxingpping** [comment]
@junlinmessi smallest granularity is task.

**Comment by PaiPratiksha** [comment]
does this PR handle "pause" Python Taskflow after a "failure" before "reverting"?

**Comment by fran6co** [comment]
Why was this PR closed?

**Pull request closed without merging**
